# Build upon this project https://github.com/samba-in-kubernetes/samba-container 
# did some changes to config and created as deployment
# change all FONTEX.LOCAL to your ad domain and add password for a bind account
# it requires a reverser-lookup zone on your dns!
# create a service and expose the pod
#kubectl expose pod <podname -n smb --port=445 --type=ClusterIP
# to access it external edit the svc and in the bottom add
#externalIPs:
#- <ip-address>
# now you can mount the smb at \\<ip-address\webfile 
apiVersion: v1
data:
  config.json: |-
    {
        "samba-container-config": "v0",
        "configs": {
                "webfile": {
                        "shares": [
                                "webfile"
                        ],
                        "globals": [
                                "globals",
                                "FONTEX.LOCAL"
                        ],
                        "instance_name": "webfile"
                }
        },
        "shares": {
                "webfile": {
                        "options": {
                                "path": "/mnt/378204f3-70ea-4e51-8bde-821057d6c378",
                                "read only": "no",
                                "valid users": "rof, FONTEX/rof, FONTEX/Administrator"
                        }
                }
        },
        "globals": {
                "FONTEX.LOCAL": {
                        "options": {
                                "idmap config * : backend": "autorid",
                                "log level": "5",
                                "idmap config * : range": "2000-9999999",
                                "realm": "FONTEX.LOCAL",
                                "security": "ads",
                                "workgroup": "FONTEX",
                                "winbind refresh tickets": "Yes",
                                "vfs objects": "acl_xattr",
                                "map acl inherit": "Yes",
                                "winbind use default domain": "yes",
                                "winbind enum users": "yes",
                                "winbind enum groups": "yes"

                        }
                },
                "globals": {
                        "options": {
                                "disable spoolss": "yes",
                                "dos charset": "ascii",
                                "fileid:algorithm": "fsid",
                                "load printers": "no",
                                "server min protocol": "SMB2",
                                "printcap name": "/dev/null",
                                "printing": "bsd",
                                "smb ports": "445",
                                "vfs objects": "fileid"
                        }
                }
        }
    }
kind: ConfigMap
metadata:
  name: webfile
  namespace: smb
---
apiVersion: v1
kind: Secret
metadata:
  name: join1
  namespace: smb
type: Opaque
stringData:
  # Change the value below to match the username and password for a user that
  # can join systems your test AD Domain
  join.json: |
    {"username": "Administrator", "password": "<password>"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samba
  name: webfile
  namespace: smb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - args:
        - run
        - smbd
        command:
        - samba-container
        env:
        - name: SAMBA_CONTAINER_ID
          value: webfile
        - name: SAMBACC_CONFIG
          value: /etc/container-config/config.json
        - name: SAMBA_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SAMBA_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/samba.org/samba-server:latest
        imagePullPolicy: Always
        name: samba
        ports:
        - containerPort: 445
          name: smb
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/container-config
          name: samba-container-config
        - mountPath: /var/lib/samba
          name: samba-state-dir
        - mountPath: /run/samba/winbindd
          name: samba-wb-sockets-dir
        - mountPath: /mnt/378204f3-70ea-4e51-8bde-821057d6c378
          name: webfile-pvc-smb
      - args:
        - run
        - winbindd
        env:
        - name: SAMBA_CONTAINER_ID
          value: webfile
        - name: SAMBACC_CONFIG
          value: /etc/container-config/config.json
        - name: SAMBA_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SAMBA_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/samba.org/samba-server:latest
        imagePullPolicy: Always
        name: wb
        volumeMounts:
        - mountPath: /etc/container-config
          name: samba-container-config
        - mountPath: /var/lib/samba
          name: samba-state-dir
        - mountPath: /run/samba/winbindd
          name: samba-wb-sockets-dir
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - init
        env:
        - name: SAMBA_CONTAINER_ID
          value: webfile
        - name: SAMBACC_CONFIG
          value: /etc/container-config/config.json
        - name: SAMBA_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SAMBA_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/samba.org/samba-server:latest
        imagePullPolicy: Always
        name: init
        volumeMounts:
        - mountPath: /etc/container-config
          name: samba-container-config
        - mountPath: /var/lib/samba
          name: samba-state-dir
      - args:
        - ensure-share-paths
        env:
        - name: SAMBA_CONTAINER_ID
          value: webfile
        - name: SAMBACC_CONFIG
          value: /etc/container-config/config.json
        - name: SAMBA_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SAMBA_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/samba.org/samba-server:latest
        imagePullPolicy: Always
        name: ensure-share-paths
        volumeMounts:
        - mountPath: /etc/container-config
          name: samba-container-config
        - mountPath: /var/lib/samba
          name: samba-state-dir
        - mountPath: /run/samba/winbindd
          name: samba-wb-sockets-dir
        - mountPath: /mnt/378204f3-70ea-4e51-8bde-821057d6c378
          name: webfile-pvc-smb
      - args:
        - must-join
        env:
        - name: SAMBA_CONTAINER_ID
          value: webfile
        - name: SAMBACC_CONFIG
          value: /etc/container-config/config.json
        - name: SAMBA_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SAMBA_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SAMBACC_JOIN_FILES
          value: /var/tmp/join/0/join.json
        image: quay.io/samba.org/samba-server:latest
        imagePullPolicy: Always
        name: must-join
        volumeMounts:
        - mountPath: /etc/container-config
          name: samba-container-config
        - mountPath: /var/lib/samba
          name: samba-state-dir
        - mountPath: /var/tmp/join/0
          name: join-data-0
      restartPolicy: Always
      schedulerName: default-scheduler
      shareProcessNamespace: true
      volumes:
      - configMap:
          defaultMode: 420
          name: webfile
        name: samba-container-config
      - emptyDir: {}
        name: samba-state-dir
      - emptyDir:
          medium: Memory
        name: samba-wb-sockets-dir
      - name: webfile-pvc-smb
        persistentVolumeClaim:
          claimName: webfile-pvc
      - name: join-data-0
        secret:
          defaultMode: 420
          items:
          - key: join.json
            path: join.json
          secretName: join1
