apiVersion: v1
data:
  config.json: |-
    {
      "samba-container-config": "v0",
      "configs": {
        "myshare": {
          "shares": [
            "myshare"
          ],
          "globals": [
            "globals",
            "<domain>"
          ],
          "instance_name": "myshare",
          "permissions": {
            "method": "initialize-share-perms",
            "status_xattr": "user.share-perms-status",
            "mode": "0777"
          }
        }
      },
      "shares": {
        "myshare": {
          "options": {
            "path": "/mnt/378204f3-70ea-4e51-8bde-821057d6c378",
            "read only": "no"
          }
        }
      },
      "globals": {
        "<domain-capital>": {
          "options": {
            "idmap config * : backend": "autorid",
            "idmap config * : range": "2000-9999999",
            "realm": "<domain-capitals>",
            "security": "ads",
            "workgroup": "<domain>"
          }
        },
        "globals": {
          "options": {
            "disable spoolss": "yes",
            "dos charset": "ascii",
            "fileid:algorithm": "fsid",
            "load printers": "no",
            "printcap name": "/dev/null",
            "printing": "bsd",
            "smb ports": "445",
            "vfs objects": "fileid"
          }
        }
      },
      "users": {
        "all_entries": [
          {
            "name": "sambauser",
            "password": "samba"
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-15T12:21:49Z"
  name: myshare
  namespace: mynamespace
  ownerReferences:
  - apiVersion: samba-operator.samba.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: SmbShare
    name: myshare
