apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: ops-services
  labels:
    app: mysqldb
    env: ops-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

