apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cluster-collector
  namespace: checkmk-monitoring
  annotations:
    kubernetes.io/service-account.name: "cluster-collector"
